# Generated by Django 4.2.7 on 2023-12-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_assist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('input_path', models.CharField(max_length=255)),
                ('output_path', models.CharField(max_length=255)),
                ('processed_line', models.IntegerField()),
                ('total_line', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('status_content', models.CharField(max_length=255)),
            ],
        ),
    ]
