# Generated by Django 4.2.7 on 2024-01-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_assist', '0004_user_kdxf_appid_user_kdxf_key_user_kdxf_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
